In [1]:
!pip install h5py


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip install librosa


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install resampy


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
!pip install Flask


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
import librosa
import resampy
from tensorflow.keras.models import load_model
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
import pandas as pd

# Load the saved model
model = load_model('model\model_checkpoint123.h5')

# Define a function to preprocess audio similar to your training data
def preprocess_audio(audio_path):
    audio, sample_rate = librosa.load(audio_path, res_type='kaiser_fast')
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T, axis=0)
    return mfccs_scaled_features

# Path to the audio file you want to classify
audio_file_path = 'wav_file\Streamlined Frog_Testing_(1).wav'

# Preprocess the input audio
input_features = preprocess_audio(audio_file_path)
input_features = np.expand_dims(input_features, axis=0)  # Add a batch dimension

print(input_features)

# Load the class labels from your CSV file or use the same labels used in training
metadata = pd.read_csv('csv file\Book1.csv')
class_labels = metadata['Species'].unique()

print(class_labels)

# Create a label encoder and fit it with the class labels
labelencoder = LabelEncoder()
labelencoder.fit(class_labels)

# Make predictions using the loaded model
predictions = model.predict(input_features)

print(predictions)
# Inverse transform the label encoding to get the predicted class
predicted_class = labelencoder.inverse_transform(np.argmax(predictions, axis=1))

if predicted_class == 0:
    print("Predicted Class:", predicted_class)
    print("Class of the frog is: Indian Skipper Frog")
elif predicted_class == 1:
    print("Predicted Class:", predicted_class)
    print("Class of the frog is: Common Shrub Frog")
elif predicted_class == 2:
    print("Predicted Class:", predicted_class)
    print("Class of the frog is: Stream lined Frog")
elif predicted_class == 3:
    print("Predicted Class:", predicted_class)
    print("Class of the frog is: Rohan's Globular Frog")

[[-4.7930688e+02  3.3591377e+01 -9.7077881e+01  2.3700635e+00
   3.1434282e+01  6.2042217e+00  1.4069927e+01  1.8935783e+01
  -3.0297949e+00 -1.2422903e+01  2.0809381e+00  1.6302244e+01
  -7.8942782e-01  2.1725557e+00  1.1287567e+01  3.1281388e-03
  -1.8840927e+00  3.1845334e+00 -1.2717131e+00 -2.1490655e+00
   4.9932556e+00  5.9189594e-01 -1.4628373e+00 -1.2132211e+00
  -1.0034363e+00  3.4635222e-01  5.2200282e-01 -4.0775051e+00
  -3.8355372e+00  1.2214981e+00  9.0390009e-01 -2.7659383e+00
  -2.6997206e+00 -3.6031213e-01 -2.5491524e+00 -4.9156663e-01
   5.8847897e-02 -2.6864188e+00 -1.5710214e+00  1.8359640e-01]]
[1 0 3 2]
1/1 [==============================] - 1s 752ms/step
[[2.0269938e-02 2.9469345e-06 9.7972715e-01]]
Predicted Class: [2]
Class of the frog is: Stream lined Frog


In [6]:
import numpy as np
import csv

with open('csv file\Book1.csv', 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    
    # Skip the header row if it exists
    next(csv_reader, None)
    
    # Extract data from the desired column (index 1 in this example)
    column_data = [row[1] for row in csv_reader]

np_array = np.array(column_data)
np.save('csv file/classes.npy', np_array)

print(np_array)


['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0' '0

In [7]:
import os
import numpy as np
from flask import Flask, request, jsonify
from tensorflow.keras.models import load_model
import librosa
import librosa.display

app = Flask(__name__)

# Load the trained model
model_path = 'model_checkpoint_newtrained.h5'
loaded_model = load_model(model_path)

# Load the label encoder
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
# Load label encoder classes
labelencoder.classes_ = np.load('csv file\classes.npy')

def preprocess_audio(file_path):
    audio, sample_rate = librosa.load(file_path, res_type='kaiser_fast')
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T, axis=0)
    return mfccs_scaled_features

@app.route('/classify-audio', methods=['POST'])
def classify_audio():
    if 'audio' not in request.files:
        return jsonify({"error": "No audio file provided"})

    audio_file = request.files['audio']

    if audio_file.filename == '':
        return jsonify({"error": "Empty audio file name"})

    try:
        input_features = preprocess_audio(audio_file)
        input_features = np.expand_dims(input_features, axis=0)  # Add a batch dimension

        print(input_features)

        # Load the class labels from your CSV file or use the same labels used in training
        metadata = pd.read_csv('csv file\Book1.csv')
        class_labels = metadata['Species'].unique()

        print(class_labels)

        # Create a label encoder and fit it with the class labels
        labelencoder = LabelEncoder()
        labelencoder.fit(class_labels)

        # Make predictions using the loaded model
        predictions = model.predict(input_features)

        print(predictions)
        # Inverse transform the label encoding to get the predicted class
        predicted_class = int(labelencoder.inverse_transform(np.argmax(predictions, axis=1)))
        return jsonify({"class": predicted_class})
    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.8.149:5000
Press CTRL+C to quit


[[-2.74455933e+02  1.08778580e+02 -3.52235565e+01  4.91433258e+01
  -3.31224251e+01  2.13042221e+01 -3.14051437e+01  2.10084510e+00
  -8.57734299e+00 -1.07206106e+01  3.91481972e+00 -1.75359802e+01
   6.42898083e+00 -1.36887245e+01  2.60674453e+00 -1.03318968e+01
  -1.43234849e+00 -2.96534801e+00 -8.93621635e+00  1.60047448e+00
  -9.26586533e+00  2.12501860e+00 -8.78726673e+00  5.47287762e-01
  -1.78198528e+00  3.36142123e-01  4.20001745e+00  1.03211844e+00
   6.04059505e+00 -1.36657023e+00  3.94792461e+00 -2.47413516e+00
  -3.37925404e-01 -1.75649238e+00 -2.06783342e+00 -1.42254436e+00
  -3.40337610e+00 -2.59722650e-01 -4.05834150e+00  2.60878593e-01]]
[1 0 3 2]
1/1 [==============================] - 0s 65ms/step


C:\Users\samee\AppData\Local\Temp\ipykernel_19148\2608205571.py:57: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predicted_class = int(labelencoder.inverse_transform(np.argmax(predictions, axis=1)))
192.168.137.15 - - [01/Nov/2023 13:05:22] "POST /classify-audio HTTP/1.1" 200 -


[[1.0000000e+00 6.8099198e-12 1.6789052e-09]]
[[-328.02838     144.92273     -52.876835     60.92563     -42.776745
    37.537914    -31.753841      9.050543     -8.51643      -8.739603
     7.9603815   -18.198483     12.815205    -12.163446      9.1262665
    -8.7001095     4.8120728     0.97455      -4.271381      3.3725924
    -7.6448936     4.472234    -11.615185      2.803228     -4.547663
     0.37116566    0.5630235    -0.72119737    4.443641     -3.849355
     5.101619     -3.9801743     1.503508     -3.7218695    -1.2440597
    -1.9573526    -3.080693      1.7237481    -4.136771      1.6246748 ]]
[1 0 3 2]
1/1 [==============================] - 0s 78ms/step


C:\Users\samee\AppData\Local\Temp\ipykernel_19148\2608205571.py:57: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predicted_class = int(labelencoder.inverse_transform(np.argmax(predictions, axis=1)))
192.168.137.15 - - [01/Nov/2023 13:05:38] "POST /classify-audio HTTP/1.1" 200 -


[[1.000000e+00 7.584273e-16 6.199923e-12]]
[[-2.9080371e+02  1.1599185e+02 -4.9604313e+01  6.1273922e+01
  -4.7006042e+01  3.7022648e+01 -3.9189861e+01  9.0048208e+00
  -1.2387198e+01 -1.0321306e+01  7.5757451e+00 -1.9761154e+01
   1.3174659e+01 -1.2798705e+01  1.1093096e+01 -8.1985521e+00
   1.8505012e+00 -2.8566811e+00 -2.3338420e+00  3.9253883e+00
  -1.0375906e+01  3.4338243e+00 -9.8342552e+00  1.9089370e+00
  -6.5619206e+00 -5.6342822e-01 -2.3063898e+00 -6.1805409e-01
   4.0021753e+00 -4.4228978e+00  3.3787158e+00 -4.4861555e+00
  -3.1099286e-02 -4.5454817e+00 -1.0484967e+00 -3.8109818e+00
  -1.6459168e+00 -1.2531523e+00 -3.4878309e+00  2.9566038e+00]]
[1 0 3 2]
1/1 [==============================] - 0s 53ms/step


C:\Users\samee\AppData\Local\Temp\ipykernel_19148\2608205571.py:57: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  predicted_class = int(labelencoder.inverse_transform(np.argmax(predictions, axis=1)))
192.168.137.15 - - [01/Nov/2023 13:05:51] "POST /classify-audio HTTP/1.1" 200 -


[[1.0000000e+00 1.8265440e-13 1.6537552e-10]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
